using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Windows.Forms.DataVisualization.Charting;

namespace InvestmentOptions {

    public class BankAccountGraph : Form {
        private Chart chart1;
        private IContainer components = null;

        public BankAccountGraph() {
            ChartArea chartArea1 = new ChartArea();
            Series series1 = new Series();
            series1.ChartType = SeriesChartType.FastLine;
            //series1.Points = data; cannot do, Points is read only... 
            series1.Points.AddY(60);
            series1.Points.AddY(50);
            chart1 = new Chart();
            chart1.ChartAreas.Add(chartArea1);
            //chart1.Location = new Point(12, 12);
            chart1.Series.Add(series1);
            //chart1.Size = new Size(300, 300);
            chart1.Text = "chart1";
            ClientSize = new Size(400, 400);
            Controls.Add(chart1);
            Text = "Christiaan Graph";
            InitializeComponent(); //this is the method that is autogenerated by VStudio.
        }
        
       /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent() {
        }

    }
}